apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: feast
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-admin-binding
subjects:
- kind: ServiceAccount
  name: app
  namespace: feast
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poc-app
  name: poc-app
  namespace: feast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      serviceAccountName: app
      containers:
      - command:
        - /bin/bash
        - -c
        - while true; do sleep 86400; done
        image: python:3.9
        name: poc-app
        ports:
        - name: app
          containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: poc-app
  namespace: feast
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: app
  selector:
    app: poc-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: a-reader
  namespace: feast
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: b-reader
  namespace: feast
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: a-editor
  namespace: feast
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: b-editor
  namespace: feast